name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 7.1.0
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^6.0.2+1
  meta: ^1.7.0
  photo_manager: ^2.0.7
  provider: ^6.0.1
  video_player: ^2.2.14
